// Public API of the virtualNodes module — see src/host/index.ts (in the
// editor app) for the pattern; same discipline applies here inside
// @synflow/core. VirtualNodeFactory.ts and AudioGraphManager.ts are the only
// consumers, both within this package. VirtualNode.ts is the shared base
// class every one of these extends — used internally only, not part of the
// public surface. VirtualAudioBufferSourceNode, VirtualCustomNode,
// VirtualFrequencyShifterNode and VirtualOrchestratorNode are dead code
// (referenced nowhere, even internally) — left out.

export * from './VirtualADSRNode';
export { default as VirtualADSRNode } from './VirtualADSRNode';
export * from './VirtualAnalyzerNodeGPT';
export { default as VirtualAnalyzerNodeGPT } from './VirtualAnalyzerNodeGPT';
export * from './VirtualArpeggiatorNode';
export { default as VirtualArpeggiatorNode } from './VirtualArpeggiatorNode';
export * from './VirtualAudioSignalFreqShifterNode';
export { default as VirtualAudioSignalFreqShifterNode } from './VirtualAudioSignalFreqShifterNode';
export * from './VirtualAudioWorkletNode';
export * from './VirtualAudioWorkletOscillatorNode';
export { default as VirtualAudioWorkletOscillatorNode } from './VirtualAudioWorkletOscillatorNode';
export * from './VirtualAutomationNode';
export { default as VirtualAutomationNode } from './VirtualAutomationNode';
export * from './VirtualBiquadFilterNode';
export { default as VirtualBiquadFilterNode } from './VirtualBiquadFilterNode';
export * from './VirtualBlockingSwitchNode';
export { default as VirtualBlockingSwitchNode } from './VirtualBlockingSwitchNode';
export * from './VirtualBrassNode';
export { default as VirtualBrassNode } from './VirtualBrassNode';
export * from './VirtualButtonNode';
export { default as VirtualButtonNode } from './VirtualButtonNode';
export * from './VirtualChorusNode';
export { default as VirtualChorusNode } from './VirtualChorusNode';
export * from './VirtualClockNode';
export { default as VirtualClockNode } from './VirtualClockNode';
export * from './VirtualCommandInNode';
export { default as VirtualCommandInNode } from './VirtualCommandInNode';
export * from './VirtualCommandOutNode';
export { default as VirtualCommandOutNode } from './VirtualCommandOutNode';
export * from './VirtualConstantNode';
export { default as VirtualConstantNode } from './VirtualConstantNode';
export * from './VirtualDelayNode';
export { default as VirtualDelayNode } from './VirtualDelayNode';
export * from './VirtualDistortionNode';
export { default as VirtualDistortionNode } from './VirtualDistortionNode';
export * from './VirtualDynamicCompressorNode';
export { default as VirtualDynamicCompressorNode } from './VirtualDynamicCompressorNode';
export * from './VirtualEnvGenNode';
export { default as VirtualEnvGenNode } from './VirtualEnvGenNode';
export * from './VirtualEqualizerNode';
export { default as VirtualEqualizerNode } from './VirtualEqualizerNode';
export * from './VirtualEventNode';
export { default as VirtualEventNode } from './VirtualEventNode';
export * from './VirtualFMNode';
export { default as VirtualFMNode } from './VirtualFMNode';
export * from './VirtualFlowEventFreqShifterNode';
export { default as VirtualFlowEventFreqShifterNode } from './VirtualFlowEventFreqShifterNode';
export * from './VirtualFlowNode';
export { default as VirtualFlowNode } from './VirtualFlowNode';
export * from './VirtualFrequencyNode';
export { default as VirtualFrequencyNode } from './VirtualFrequencyNode';
export * from './VirtualFunctionNode';
export { default as VirtualFunctionNode } from './VirtualFunctionNode';
export * from './VirtualGainNode';
export { default as VirtualGainNode } from './VirtualGainNode';
export * from './VirtualGranularNode';
export { default as VirtualGranularNode } from './VirtualGranularNode';
export * from './VirtualIIRFilterNode';
export { default as VirtualIIRFilterNode } from './VirtualIIRFilterNode';
export * from './VirtualInputNode';
export { default as VirtualInputNode } from './VirtualInputNode';
export * from './VirtualKarplusNode';
export { default as VirtualKarplusNode } from './VirtualKarplusNode';
export * from './VirtualLadderFilterNode';
export { default as VirtualLadderFilterNode } from './VirtualLadderFilterNode';
export * from './VirtualLogNode';
export { default as VirtualLogNode } from './VirtualLogNode';
export * from './VirtualMasterOut';
export { default as VirtualMasterOut } from './VirtualMasterOut';
export * from './VirtualMicNode';
export { default as VirtualMicNode } from './VirtualMicNode';
export * from './VirtualMidiButtonNode';
export { default as VirtualMidiButtonNode } from './VirtualMidiButtonNode';
export * from './VirtualMidiFileNode';
export { default as VirtualMidiFileNode } from './VirtualMidiFileNode';
export * from './VirtualMidiKnobNode';
export { default as VirtualMidiKnobNode } from './VirtualMidiKnobNode';
export * from './VirtualMidiNode';
export { default as VirtualMidiNode } from './VirtualMidiNode';
export * from './VirtualMouseTriggerButtonNode';
export { default as VirtualMouseTriggerButtonNode } from './VirtualMouseTriggerButtonNode';
export * from './VirtualNoiseNode';
export { default as VirtualNoiseNode } from './VirtualNoiseNode';
export * from './VirtualOnOffButtonNode';
export { default as VirtualOnOffButtonNode } from './VirtualOnOffButtonNode';
export * from './VirtualOscillatorNode';
export { default as VirtualOscillatorNode } from './VirtualOscillatorNode';
export * from './VirtualOscilloscopeNode';
export { default as VirtualOscilloscopeNode } from './VirtualOscilloscopeNode';
export * from './VirtualOutputNode';
export { default as VirtualOutputNode } from './VirtualOutputNode';
export * from './VirtualRecordingNode';
export { default as VirtualRecordingNode } from './VirtualRecordingNode';
export * from './VirtualReverbNode';
export { default as VirtualReverbNode } from './VirtualReverbNode';
export * from './VirtualRingModNode';
export { default as VirtualRingModNode } from './VirtualRingModNode';
export * from './VirtualSampleFlowNode';
export { default as VirtualSampleFlowNode } from './VirtualSampleFlowNode';
export * from './VirtualScriptSequencerNode';
export { default as VirtualScriptSequencerNode } from './VirtualScriptSequencerNode';
export * from './VirtualSequencerFrequencyNode';
export { default as VirtualSequencerFrequencyNode } from './VirtualSequencerFrequencyNode';
export * from './VirtualSequencerNode';
export { default as VirtualSequencerNode } from './VirtualSequencerNode';
export * from './VirtualSpeedDividerNode';
export { default as VirtualSpeedDividerNode } from './VirtualSpeedDividerNode';
export * from './VirtualSvfDriveFilterNode';
export { default as VirtualSvfDriveFilterNode } from './VirtualSvfDriveFilterNode';
export * from './VirtualSwitchNode';
export { default as VirtualSwitchNode } from './VirtualSwitchNode';
export * from './VirtualUnisonBeginNode';
export { default as VirtualUnisonBeginNode } from './VirtualUnisonBeginNode';
export * from './VirtualUnisonEndNode';
export { default as VirtualUnisonEndNode } from './VirtualUnisonEndNode';
export * from './VirtualVocoderNode';
export { default as VirtualVocoderNode } from './VirtualVocoderNode';
export * from './VirtualVstaiNode';
export { default as VirtualVstaiNode } from './VirtualVstaiNode';
export * from './VirtualWavetableNode';
export { default as VirtualWavetableNode } from './VirtualWavetableNode';
export * from './VirtualWebRTCInputNode';
export { default as VirtualWebRTCInputNode } from './VirtualWebRTCInputNode';
export * from './VirtualWebRTCOutputNode';
export { default as VirtualWebRTCOutputNode } from './VirtualWebRTCOutputNode';
